### ISSUE TITLE
Add support to single `#` as the version header

### ISSUE THREAD

**Issue by fsmaia** [parkr/changelog#9]
Some changelog presets, like [conventional-changelog-angular](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular), use `#` as the version header.

By the way, in this particular preset, both `#` and `##` are used as version headers (`##` for patches, `#` for the other version types).

Instead of adding a parser preset and add complexity to the project, we could just support these two header levels.

I could create a PR if you agree with that :)

**Comment by parkr** [comment]
Sounds good to me!
